set background=dark
"colorscheme solarized
set termguicolors
" AutoGenerated config below here
"set number		" Show line numbers
set showbreak=+++	" Wrap-broken line prefix
set showmatch		" Highlight matching brace
set visualbell		" Use visual bell (no beeping)

set hlsearch		" Highlight all search results
set smartcase		" Enable smart-case search
set ignorecase		" Always case-insensitive
set incsearch		" Searches for strings incrementally

set autoindent		" Auto-indent new lines
set shiftwidth=4	" Number of auto-indent spaces
set smartindent		" Enable smart-indent
set smarttab		" Enable smart-tabs
set noexpandtab
set tabstop=4
set softtabstop=4	" Number of spaces per Tab

" Advanced
set ruler		" Show row and column ruler information

set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

"
" START PLUGINS
"

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'powerline/powerline'

" Initialize plugin system
call plug#end()
"
" END PLUGINS
"
"
" Configure themes
let g:airline_powerline_fonts = 1
let g:airline_theme = 'simple' 
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

